package io.multi.notificationserver.enumeration;

public enum EventType {
    RESETPASSWORD, USER_CREATED, STOCK_VALIDATED, STOCK_REJECTED, NEW_MESSAGE, TICKET_CREATED, COMMENT_CREATED, FILE_UPLOADED, ACCOUNT_VERIFIED, COMMANDE_CONFIRMEE, COMMANDE_ANNULEE,
    REMPLISSAGE_50, REMPLISSAGE_75, REMPLISSAGE_100, RAPPEL_J1, RAPPEL_H2, BILLET_VALIDE
}
